function task03_thermal_quantum_models()
% TASK03_THERMAL_QUANTUM_MODELS
% BPhO Computational Physics Challenge 2026 - Task 3
%
% Interactive comparison of:
%   1) Planck's black-body radiation law
%   2) Einstein's model of molar heat capacity
%
% The program combines the clear plots from BBRbasic.m with the interactive
% tabbed layout from BlackBodyRadiation.m, while correcting the legend,
% units, peak calculation and numerical stability.
%
% Run from the Command Window with:
%   task03_thermal_quantum_models

close all;
clc;

%% Physical constants (exact SI values where defined)
h      = 6.62607015e-34;       % Planck constant / J s
c      = 299792458;            % Speed of light / m s^-1
kB     = 1.380649e-23;         % Boltzmann constant / J K^-1
R      = 8.31446261815324;      % Molar gas constant / J mol^-1 K^-1
bWien  = 2.897771955e-3;        % Wien displacement constant / m K

%% Default data
planckTemperatures = [3000 4000 5000 6000];

% Einstein temperatures in kelvin.
% Au, Cu and Fe retain the values used in the original challenge drafts.
% The additional values are representative comparison values; the array is
% deliberately placed here so they can easily be replaced by values from a
% preferred reference source.
materialNames = { ...
    'Gold (Au)', ...
    'Copper (Cu)', ...
    'Iron (Fe)', ...
    'Silver (Ag)', ...
    'Aluminium (Al)', ...
    'Lead (Pb)', ...
    'Tungsten (W)', ...
    'Nickel (Ni)'};

thetaEinstein = [165 230 430 225 300 105 400 450];

%% Main window
fig = figure( ...
    'Name', 'Task 3: Thermal Quantum Models', ...
    'NumberTitle', 'off', ...
    'Color', 'w', ...
    'Position', [80 80 1260 740], ...
    'Resize', 'on');

mainTabs = uitabgroup('Parent', fig);
planckTab = uitab('Parent', mainTabs, 'Title', 'Planck spectrum');
einsteinTab = uitab('Parent', mainTabs, 'Title', 'Einstein heat capacity');

%% ========================================================================
% TAB 1: PLANCK BLACK-BODY RADIATION
% =========================================================================
planckAxes = axes( ...
    'Parent', planckTab, ...
    'Units', 'normalized', ...
    'Position', [0.07 0.30 0.66 0.64]);

planckTable = uitable( ...
    'Parent', planckTab, ...
    'Units', 'normalized', ...
    'Position', [0.07 0.055 0.66 0.18], ...
    'ColumnName', {'T / K', 'Numerical peak / nm', ...
                   'Wien peak / nm', 'Difference / %'}, ...
    'ColumnEditable', false(1,4), ...
    'RowName', []);

planckPanel = uipanel( ...
    'Parent', planckTab, ...
    'Units', 'normalized', ...
    'Position', [0.76 0.055 0.22 0.885], ...
    'Title', 'Temperatures and display', ...
    'FontWeight', 'bold', ...
    'BackgroundColor', 'w');

uicontrol( ...
    'Parent', planckPanel, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.07 0.91 0.86 0.05], ...
    'String', 'Temperatures currently plotted:', ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', 'w');

planckList = uicontrol( ...
    'Parent', planckPanel, ...
    'Style', 'listbox', ...
    'Units', 'normalized', ...
    'Position', [0.07 0.64 0.86 0.27], ...
    'Min', 0, ...
    'Max', 20, ...
    'Value', 1);

uicontrol( ...
    'Parent', planckPanel, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.07 0.565 0.86 0.05], ...
    'String', 'Add a temperature (K):', ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', 'w');

planckTemperatureEdit = uicontrol( ...
    'Parent', planckPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized', ...
    'Position', [0.07 0.515 0.52 0.055], ...
    'String', '4500', ...
    'BackgroundColor', 'w');

uicontrol( ...
    'Parent', planckPanel, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.62 0.515 0.31 0.055], ...
    'String', 'Add', ...
    'Callback', @addPlanckTemperature);

uicontrol( ...
    'Parent', planckPanel, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.07 0.435 0.41 0.06], ...
    'String', 'Remove selected', ...
    'Callback', @removePlanckTemperature);

uicontrol( ...
    'Parent', planckPanel, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.52 0.435 0.41 0.06], ...
    'String', 'Reset', ...
    'Callback', @resetPlanckTemperatures);

visibleBandCheck = uicontrol( ...
    'Parent', planckPanel, ...
    'Style', 'checkbox', ...
    'Units', 'normalized', ...
    'Position', [0.07 0.35 0.86 0.06], ...
    'String', 'Shade visible range (380-750 nm)', ...
    'Value', 1, ...
    'BackgroundColor', 'w', ...
    'Callback', @(~,~) updatePlanckPlot());

uicontrol( ...
    'Parent', planckPanel, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.07 0.08 0.86 0.23], ...
    'String', { ...
        'Validation:', ...
        'The numerical maximum of each', ...
        'calculated spectrum is compared', ...
        'with Wien''s law:', ...
        'lambda_max T = b.'}, ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', 'w');

%% ========================================================================
% TAB 2: EINSTEIN HEAT CAPACITY
% =========================================================================
einsteinAxes = axes( ...
    'Parent', einsteinTab, ...
    'Units', 'normalized', ...
    'Position', [0.07 0.13 0.68 0.80]);

einsteinPanel = uipanel( ...
    'Parent', einsteinTab, ...
    'Units', 'normalized', ...
    'Position', [0.78 0.055 0.20 0.885], ...
    'Title', 'Crystal selection', ...
    'FontWeight', 'bold', ...
    'BackgroundColor', 'w');

uicontrol( ...
    'Parent', einsteinPanel, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.07 0.91 0.86 0.05], ...
    'String', 'Select one or more materials:', ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', 'w');

materialList = uicontrol( ...
    'Parent', einsteinPanel, ...
    'Style', 'listbox', ...
    'Units', 'normalized', ...
    'Position', [0.07 0.53 0.86 0.38], ...
    'String', makeMaterialLabels(), ...
    'Min', 0, ...
    'Max', numel(materialNames), ...
    'Value', 1:3, ...
    'Callback', @(~,~) updateEinsteinPlot());

uicontrol( ...
    'Parent', einsteinPanel, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.07 0.455 0.86 0.05], ...
    'String', 'Maximum temperature (K):', ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', 'w');

maximumTemperatureEdit = uicontrol( ...
    'Parent', einsteinPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized', ...
    'Position', [0.07 0.405 0.50 0.055], ...
    'String', '800', ...
    'BackgroundColor', 'w');

uicontrol( ...
    'Parent', einsteinPanel, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.61 0.405 0.32 0.055], ...
    'String', 'Update', ...
    'Callback', @(~,~) updateEinsteinPlot());

uicontrol( ...
    'Parent', einsteinPanel, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.07 0.325 0.86 0.06], ...
    'String', 'Select Au, Cu and Fe', ...
    'Callback', @selectDefaultMaterials);

uicontrol( ...
    'Parent', einsteinPanel, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.07 0.065 0.86 0.22], ...
    'String', { ...
        'The dashed line is 3R, the', ...
        'Dulong-Petit high-temperature', ...
        'limit. Different Einstein', ...
        'temperatures control how rapidly', ...
        'each crystal approaches 3R.'}, ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', 'w');

%% Initial plots
updatePlanckList();
updatePlanckPlot();
updateEinsteinPlot();

%% ========================================================================
% NESTED CALLBACK AND CALCULATION FUNCTIONS
% =========================================================================
    function updatePlanckList()
        labels = arrayfun(@(T) sprintf('%.0f K', T), ...
            planckTemperatures, 'UniformOutput', false);
        set(planckList, 'String', labels);

        currentValue = get(planckList, 'Value');
        if isempty(labels)
            set(planckList, 'Value', []);
        else
            currentValue = currentValue(currentValue <= numel(labels));
            if isempty(currentValue)
                currentValue = 1;
            end
            set(planckList, 'Value', currentValue);
        end
    end

    function addPlanckTemperature(~,~)
        newTemperature = str2double(get(planckTemperatureEdit, 'String'));

        if ~isfinite(newTemperature) || newTemperature < 500 || ...
                newTemperature > 20000
            errordlg(['Enter a temperature between 500 K and 20000 K. ' ...
                      'This range keeps the selected wavelength window useful.'], ...
                     'Invalid temperature');
            return;
        end

        if any(abs(planckTemperatures - newTemperature) < 1e-9)
            errordlg('That temperature is already plotted.', ...
                     'Duplicate temperature');
            return;
        end

        planckTemperatures(end+1) = newTemperature;
        planckTemperatures = sort(planckTemperatures);
        updatePlanckList();
        updatePlanckPlot();
    end

    function removePlanckTemperature(~,~)
        selected = get(planckList, 'Value');
        if isempty(selected)
            return;
        end

        if numel(selected) >= numel(planckTemperatures)
            errordlg('At least one temperature must remain.', ...
                     'Cannot remove all curves');
            return;
        end

        planckTemperatures(selected) = [];
        set(planckList, 'Value', 1);
        updatePlanckList();
        updatePlanckPlot();
    end

    function resetPlanckTemperatures(~,~)
        planckTemperatures = [3000 4000 5000 6000];
        set(planckList, 'Value', 1);
        updatePlanckList();
        updatePlanckPlot();
    end

    function updatePlanckPlot()
        cla(planckAxes);
        hold(planckAxes, 'on');

        % Plot in nm, but evaluate Planck's law using metres.
        lambdaNm = linspace(100, 3000, 3500);
        lambdaM = lambdaNm * 1e-9;

        numberOfCurves = numel(planckTemperatures);
        curveColours = lines(max(numberOfCurves, 1));
        lineHandles = gobjects(numberOfCurves, 1);
        resultData = zeros(numberOfCurves, 4);

        maximumRadiance = 0;
        radianceCurves = cell(numberOfCurves, 1);

        for index = 1:numberOfCurves
            temperature = planckTemperatures(index);
            spectralRadiance = planckPerNanometre(lambdaM, temperature);
            radianceCurves{index} = spectralRadiance;
            maximumRadiance = max(maximumRadiance, max(spectralRadiance));
        end

        if get(visibleBandCheck, 'Value') == 1 && maximumRadiance > 0
            visiblePatch = patch(planckAxes, ...
                [380 750 750 380], ...
                [0 0 1.08*maximumRadiance 1.08*maximumRadiance], ...
                [0.75 0.75 0.75], ...
                'FaceAlpha', 0.16, ...
                'EdgeColor', 'none', ...
                'HandleVisibility', 'off');
            uistack(visiblePatch, 'bottom');
            text(planckAxes, 565, 1.045*maximumRadiance, ...
                'Visible spectrum', ...
                'HorizontalAlignment', 'center', ...
                'Color', [0.35 0.35 0.35], ...
                'FontSize', 9, ...
                'HandleVisibility', 'off');
        end

        for index = 1:numberOfCurves
            temperature = planckTemperatures(index);
            spectralRadiance = radianceCurves{index};

            lineHandles(index) = plot(planckAxes, lambdaNm, spectralRadiance, ...
                'LineWidth', 2.2, ...
                'Color', curveColours(index,:), ...
                'DisplayName', sprintf('%.0f K', temperature));

            % Numerical peak from the calculated Planck curve.
            [numericalPeakRadiance, peakIndex] = max(spectralRadiance);
            numericalPeakNm = lambdaNm(peakIndex);

            % Independent theoretical prediction from Wien's displacement law.
            wienPeakNm = (bWien / temperature) * 1e9;
            percentageDifference = ...
                100 * abs(numericalPeakNm - wienPeakNm) / wienPeakNm;

            plot(planckAxes, numericalPeakNm, numericalPeakRadiance, 'o', ...
                'Color', curveColours(index,:), ...
                'MarkerFaceColor', curveColours(index,:), ...
                'MarkerSize', 6, ...
                'HandleVisibility', 'off');

            resultData(index,:) = [temperature, numericalPeakNm, ...
                                   wienPeakNm, percentageDifference];
        end

        hold(planckAxes, 'off');
        grid(planckAxes, 'on');
        box(planckAxes, 'on');
        xlim(planckAxes, [100 3000]);
        if maximumRadiance > 0
            ylim(planckAxes, [0 1.08*maximumRadiance]);
        end

        xlabel(planckAxes, 'Wavelength, \lambda (nm)');
        ylabel(planckAxes, ...
            'Spectral radiance, B_\lambda (W m^{-2} sr^{-1} nm^{-1})');
        title(planckAxes, 'Planck Black-Body Radiation Spectrum');
        legend(planckAxes, lineHandles, 'Location', 'northeast');

        set(planckTable, 'Data', resultData);
        drawnow;
    end

    function spectralRadianceNm = planckPerNanometre(lambdaMetres, temperature)
        % Planck spectral radiance per unit wavelength.
        % SI form initially gives W m^-3 sr^-1. Multiplication by 1e-9
        % converts it to W m^-2 sr^-1 nm^-1 for a nanometre x-axis.
        exponent = h*c ./ (lambdaMetres*kB*temperature);

        spectralRadiancePerMetre = zeros(size(lambdaMetres));
        safe = exponent < 700;
        spectralRadiancePerMetre(safe) = ...
            (2*h*c^2 ./ lambdaMetres(safe).^5) ./ expm1(exponent(safe));

        spectralRadianceNm = spectralRadiancePerMetre * 1e-9;
    end

    function labels = makeMaterialLabels()
        labels = cell(size(materialNames));
        for index = 1:numel(materialNames)
            labels{index} = sprintf('%s   (theta_E = %.0f K)', ...
                materialNames{index}, thetaEinstein(index));
        end
    end

    function selectDefaultMaterials(~,~)
        set(materialList, 'Value', 1:3);
        updateEinsteinPlot();
    end

    function updateEinsteinPlot()
        selectedMaterials = get(materialList, 'Value');
        maximumTemperature = str2double(get(maximumTemperatureEdit, 'String'));

        if ~isfinite(maximumTemperature) || maximumTemperature < 100 || ...
                maximumTemperature > 5000
            errordlg('Enter a maximum temperature between 100 K and 5000 K.', ...
                     'Invalid temperature range');
            set(maximumTemperatureEdit, 'String', '800');
            return;
        end

        if isempty(selectedMaterials)
            errordlg('Select at least one material.', 'No material selected');
            set(materialList, 'Value', 1:3);
            selectedMaterials = 1:3;
        end

        temperatureVector = linspace(1, maximumTemperature, 1200);
        curveColours = lines(numel(selectedMaterials));

        cla(einsteinAxes);
        hold(einsteinAxes, 'on');
        lineHandles = gobjects(numel(selectedMaterials), 1);

        for plotIndex = 1:numel(selectedMaterials)
            materialIndex = selectedMaterials(plotIndex);
            thetaE = thetaEinstein(materialIndex);
            x = thetaE ./ temperatureVector;

            % Stable version of the Einstein heat-capacity expression:
            % Cv = 3R x^2 exp(x) / (exp(x)-1)^2
            %    = 3R x^2 exp(-x) / (1-exp(-x))^2
            denominator = -expm1(-x);
            heatCapacity = 3*R .* x.^2 .* exp(-x) ./ denominator.^2;

            lineHandles(plotIndex) = plot(einsteinAxes, ...
                temperatureVector, heatCapacity, ...
                'LineWidth', 2.2, ...
                'Color', curveColours(plotIndex,:), ...
                'DisplayName', materialNames{materialIndex});
        end

        dulongPetit = 3*R;
        yline(einsteinAxes, dulongPetit, '--', ...
            sprintf('Dulong-Petit limit: 3R = %.2f J mol^{-1} K^{-1}', ...
                    dulongPetit), ...
            'LineWidth', 1.4, ...
            'LabelHorizontalAlignment', 'left', ...
            'HandleVisibility', 'off');

        hold(einsteinAxes, 'off');
        grid(einsteinAxes, 'on');
        box(einsteinAxes, 'on');
        xlim(einsteinAxes, [0 maximumTemperature]);
        ylim(einsteinAxes, [0 1.05*dulongPetit]);

        xlabel(einsteinAxes, 'Temperature, T (K)');
        ylabel(einsteinAxes, 'Molar heat capacity, C_V (J mol^{-1} K^{-1})');
        title(einsteinAxes, 'Einstein Model of Molar Heat Capacity');
        legend(einsteinAxes, lineHandles, 'Location', 'southeast');
        drawnow;
    end
end
