function ParticleInABox_Task7
% =========================================================================
%  TASK #7: PARTICLE-IN-A-BOX SOLUTION TO THE SCHRÖDINGER EQUATION
%  =========================================================================
%  Interactive MATLAB model of the infinite square well (particle in a box).
%
%  PHYSICS SUMMARY (detailed annotations throughout code)
%  -------------------------------------------------------
%  Infinite potential well: V = 0 for 0 < x < L,  V = ∞ elsewhere.
%
%  Energy eigenvalues:
%        E_n = (n² π² ħ²) / (2 m L²)     n = 1, 2, 3, ...
%
%  Normalized wave functions:
%        ψ_n(x) = √(2/L) * sin(n π x / L)     0 ≤ x ≤ L
%
%  Probability density:
%        |ψ_n(x)|² = (2/L) * sin²(n π x / L)
%
%  EXTENSION – Uncertainty Principle check:
%        Δx = √( <x²> − <x>² )
%        Δp = √( <p²> − <p>² )
%        For the infinite well <p> = 0 and the product satisfies
%        Δx Δp ≥ ħ/2
%
%  INTERACTIVE FEATURES
%  --------------------
%  • Quantum number n slider (1 – 15)
%  • Box width L slider (0.2 – 5.0 nm)
%  • Live plots of E vs n and |ψ|² vs x
%  • Overlay of multiple probability densities
%  • Real-time calculation of Δx, Δp and the product Δx·Δp
%  • Comparison with ħ/2 to demonstrate the Uncertainty Principle
%  • Theory / equations panel
%  • Export of numerical results
%
%  
%  =========================================================================

    % ----- Close any previous instance -----
    delete(findall(0, 'Type', 'figure', 'Tag', 'ParticleInABoxApp'));

    % =====================================================================
    % PHYSICAL CONSTANTS (SI units)
    % =====================================================================
    hbar = 1.054571817e-34;    % reduced Planck constant (J·s)
    m_e  = 9.1093837015e-31;   % electron mass (kg) – default particle
    eV   = 1.602176634e-19;    % 1 eV in joules (for energy conversion)

    % Default parameters
    n_default = 1;
    L_default = 1.0;           % nm

    % =====================================================================
    % CREATE MAIN FIGURE – plain light background
    % =====================================================================
    fig = uifigure( ...
        'Name',           'Particle-in-a-Box – Task #7 | Interactive Model', ...
        'Tag',            'ParticleInABoxApp', ...
        'Position',       [60 40 1320 800], ...
        'Color',          [0.94 0.94 0.94], ...
        'Resize',         'on');

    mainGrid = uigridlayout(fig, [1 2]);
    mainGrid.ColumnWidth   = {340, '1x'};
    mainGrid.Padding       = [12 12 12 12];
    mainGrid.ColumnSpacing = 14;
    mainGrid.BackgroundColor = [0.94 0.94 0.94];

    % =====================================================================
    % LEFT PANEL – CONTROLS & THEORY
    % =====================================================================
    leftPanel = uipanel(mainGrid, ...
        'Title',          '  CONTROL & THEORY PANEL', ...
        'FontName',       'Segoe UI', ...
        'FontSize',       13, ...
        'FontWeight',     'bold', ...
        'ForegroundColor',[0.1 0.1 0.1], ...
        'BackgroundColor',[0.96 0.96 0.96], ...
        'BorderType',     'line', ...
        'HighlightColor', [0.5 0.5 0.5]);

    leftGrid = uigridlayout(leftPanel, [14 1]);
    leftGrid.RowHeight = {26, 50, 26, 50, 30, 36, 26, 110, 40, 40, 40, 26, '1x', 30};
    leftGrid.Padding   = [10 10 10 10];
    leftGrid.RowSpacing = 7;
    leftGrid.BackgroundColor = [0.96 0.96 0.96];

    % --- Quantum number n ---
    uilabel(leftGrid, ...
        'Text', 'Quantum number n', ...
        'FontSize', 12, 'FontWeight', 'bold', ...
        'FontColor', [0.1 0.1 0.1], ...
        'HorizontalAlignment', 'center');

    nPanel = uigridlayout(leftGrid, [1 2]);
    nPanel.ColumnWidth = {'1x', 55};
    nPanel.Padding = [0 0 0 0];
    nPanel.BackgroundColor = [0.96 0.96 0.96];

    sldN = uislider(nPanel, ...
        'Limits', [1 15], ...
        'Value', n_default, ...
        'MajorTicks', 1:2:15, ...
        'MinorTicks', [], ...
        'FontColor', [0.2 0.2 0.2], ...
        'Tooltip', 'Select quantum number n (energy level)');

    lblN = uilabel(nPanel, ...
        'Text', sprintf('%d', n_default), ...
        'FontSize', 14, 'FontWeight', 'bold', ...
        'FontColor', [0.0 0.35 0.55], ...
        'HorizontalAlignment', 'center', ...
        'BackgroundColor', [0.90 0.93 0.97]);

    % --- Box width L ---
    uilabel(leftGrid, ...
        'Text', 'Box width L (nm)', ...
        'FontSize', 12, 'FontWeight', 'bold', ...
        'FontColor', [0.1 0.1 0.1], ...
        'HorizontalAlignment', 'center');

    LPanel = uigridlayout(leftGrid, [1 2]);
    LPanel.ColumnWidth = {'1x', 70};
    LPanel.Padding = [0 0 0 0];
    LPanel.BackgroundColor = [0.96 0.96 0.96];

    sldL = uislider(LPanel, ...
        'Limits', [0.2 5.0], ...
        'Value', L_default, ...
        'MajorTicks', [0.5 1 2 3 4 5], ...
        'FontColor', [0.2 0.2 0.2], ...
        'Tooltip', 'Width of the infinite square well (nm)');

    lblL = uilabel(LPanel, ...
        'Text', sprintf('%.2f nm', L_default), ...
        'FontSize', 13, 'FontWeight', 'bold', ...
        'FontColor', [0.0 0.4 0.15], ...
        'HorizontalAlignment', 'center', ...
        'BackgroundColor', [0.90 0.95 0.90]);

    % --- Overlay options ---
    uilabel(leftGrid, ...
        'Text', 'Display options', ...
        'FontSize', 11, 'FontWeight', 'bold', ...
        'FontColor', [0.1 0.1 0.1], ...
        'HorizontalAlignment', 'center');

    chkOverlay = uicheckbox(leftGrid, ...
        'Text', 'Show n = 1…5 probability densities together', ...
        'Value', false, ...
        'FontColor', [0.15 0.15 0.15], ...
        'FontSize', 11, ...
        'Tooltip', 'Overlay the first five |ψ|² curves');

    % --- Live calculated quantities ---
    uilabel(leftGrid, ...
        'Text', 'Live Calculated Quantities', ...
        'FontSize', 11, 'FontWeight', 'bold', ...
        'FontColor', [0.1 0.1 0.1], ...
        'HorizontalAlignment', 'center');

    txtValues = uitextarea(leftGrid, ...
        'Value', {''}, ...
        'Editable', 'off', ...
        'FontName', 'Consolas', ...
        'FontSize', 11, ...
        'FontColor', [0.1 0.1 0.1], ...
        'BackgroundColor', [1 1 1], ...
        'Tooltip', 'Energy, expectation values and uncertainty product');

    % --- Action buttons ---
    btnVerify = uibutton(leftGrid, ...
        'Text', 'Show Uncertainty Principle Check', ...
        'FontWeight', 'bold', ...
        'FontSize', 11, ...
        'BackgroundColor', [0.85 0.92 0.85], ...
        'FontColor', [0.05 0.25 0.1], ...
        'Tooltip', 'Highlight Δx·Δp versus ħ/2 for the current state');

    btnExport = uibutton(leftGrid, ...
        'Text', 'Export Numerical Results', ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.95 0.92 0.85], ...
        'FontColor', [0.3 0.2 0.05], ...
        'Tooltip', 'Save energies, wave-function data and uncertainty values');

    % --- Theory box ---
    uilabel(leftGrid, ...
        'Text', 'Key Equations', ...
        'FontSize', 11, 'FontWeight', 'bold', ...
        'FontColor', [0.1 0.1 0.1], ...
        'HorizontalAlignment', 'center');

    txtTheory = uitextarea(leftGrid, ...
        'Value', { ...
            'E_n = n² π² ħ² / (2 m L²)', ...
            'ψ_n(x) = √(2/L) sin(n π x / L)', ...
            '|ψ|² = (2/L) sin²(n π x / L)', ...
            '', ...
            'Δx = √(<x²> − <x>²)', ...
            'Δp = √(<p²> − <p>²)   (<p>=0)', ...
            'Uncertainty Principle:', ...
            '  Δx · Δp  ≥  ħ/2'}, ...
        'Editable', 'off', ...
        'FontName', 'Consolas', ...
        'FontSize', 10, ...
        'FontColor', [0.15 0.15 0.15], ...
        'BackgroundColor', [1 1 1]);

    % Status bar
    lblStatus = uilabel(leftGrid, ...
        'Text', 'Ready – adjust n or L to explore the model.', ...
        'FontSize', 10, ...
        'FontColor', [0.2 0.3 0.4], ...
        'HorizontalAlignment', 'center', ...
        'BackgroundColor', [0.92 0.92 0.92]);

    % =====================================================================
    % RIGHT PANEL – PLOTS
    % =====================================================================
    rightPanel = uipanel(mainGrid, ...
        'Title', '  ENERGY SPECTRUM  |  PROBABILITY DENSITY  |  UNCERTAINTY', ...
        'FontName', 'Segoe UI', ...
        'FontSize', 13, ...
        'FontWeight', 'bold', ...
        'ForegroundColor', [0.1 0.1 0.1], ...
        'BackgroundColor', [0.96 0.96 0.96], ...
        'BorderType', 'line', ...
        'HighlightColor', [0.5 0.5 0.5]);

    rightGrid = uigridlayout(rightPanel, [2 2]);
    rightGrid.RowHeight   = {'1x', '1.15x'};
    rightGrid.ColumnWidth = {'1x', '1x'};
    rightGrid.Padding     = [8 8 8 8];
    rightGrid.RowSpacing  = 10;
    rightGrid.ColumnSpacing = 10;
    rightGrid.BackgroundColor = [0.96 0.96 0.96];

    % Energy vs n axes
    axEnergy = uiaxes(rightGrid, ...
        'BackgroundColor', [1 1 1], ...
        'XColor', [0.2 0.2 0.2], ...
        'YColor', [0.2 0.2 0.2], ...
        'FontName', 'Segoe UI', 'FontSize', 10, ...
        'Box', 'on', 'GridColor', [0.75 0.75 0.75], 'GridAlpha', 0.5);
    title(axEnergy, 'Energy levels E_n versus quantum number n', ...
        'Color', [0.1 0.1 0.1], 'FontSize', 12, 'FontWeight', 'bold');
    xlabel(axEnergy, 'Quantum number n', 'Color', [0.2 0.2 0.2]);
    ylabel(axEnergy, 'Energy E_n (eV)', 'Color', [0.2 0.2 0.2]);
    grid(axEnergy, 'on');
    hold(axEnergy, 'on');

    % Probability density axes (spans both columns on bottom)
    axProb = uiaxes(rightGrid, ...
        'BackgroundColor', [1 1 1], ...
        'XColor', [0.2 0.2 0.2], ...
        'YColor', [0.2 0.2 0.2], ...
        'FontName', 'Segoe UI', 'FontSize', 10, ...
        'Box', 'on', 'GridColor', [0.75 0.75 0.75], 'GridAlpha', 0.5);
    axProb.Layout.Row = 2;
    axProb.Layout.Column = [1 2];
    title(axProb, 'Probability density |\psi_n(x)|² versus position x', ...
        'Color', [0.1 0.1 0.1], 'FontSize', 12, 'FontWeight', 'bold');
    xlabel(axProb, 'Position x (nm)', 'Color', [0.2 0.2 0.2]);
    ylabel(axProb, '|\psi|^{2} (1/nm)', 'Color', [0.2 0.2 0.2]);
    grid(axProb, 'on');
    hold(axProb, 'on');

    % Uncertainty summary axes (top-right)
    axUnc = uiaxes(rightGrid, ...
        'BackgroundColor', [1 1 1], ...
        'XColor', [0.2 0.2 0.2], ...
        'YColor', [0.2 0.2 0.2], ...
        'FontName', 'Segoe UI', 'FontSize', 10, ...
        'Box', 'on', 'GridColor', [0.75 0.75 0.75], 'GridAlpha', 0.5);
    title(axUnc, 'Uncertainty product Δx·Δp  vs  ħ/2', ...
        'Color', [0.1 0.1 0.1], 'FontSize', 12, 'FontWeight', 'bold');
    xlabel(axUnc, 'Quantum number n', 'Color', [0.2 0.2 0.2]);
    ylabel(axUnc, 'Δx · Δp  /  ħ', 'Color', [0.2 0.2 0.2]);
    grid(axUnc, 'on');
    hold(axUnc, 'on');

    % =====================================================================
    % CALLBACKS
    % =====================================================================
    sldN.ValueChangedFcn       = @(src,~) updateAll();
    sldL.ValueChangedFcn       = @(src,~) updateAll();
    chkOverlay.ValueChangedFcn = @(src,~) updateAll();
    btnVerify.ButtonPushedFcn  = @(src,~) highlightUncertainty();
    btnExport.ButtonPushedFcn  = @(src,~) exportResults();

    handles = struct();
    handles.sldN       = sldN;
    handles.lblN       = lblN;
    handles.sldL       = sldL;
    handles.lblL       = lblL;
    handles.chkOverlay = chkOverlay;
    handles.txtValues  = txtValues;
    handles.axEnergy   = axEnergy;
    handles.axProb     = axProb;
    handles.axUnc      = axUnc;
    handles.lblStatus  = lblStatus;
    handles.fig        = fig;

    % Initial draw
    updateAll();

    % =====================================================================
    % NESTED FUNCTIONS
    % =====================================================================

    function updateAll()
        n = round(handles.sldN.Value);
        handles.sldN.Value = n;          % snap to integer
        handles.lblN.Text  = sprintf('%d', n);

        L_nm = handles.sldL.Value;
        handles.lblL.Text = sprintf('%.2f nm', L_nm);

        L = L_nm * 1e-9;                 % convert to metres

        % ----- Energy spectrum -----
        n_vec = 1:15;
        E_eV  = energy_eV(n_vec, L, m_e);

        cla(handles.axEnergy);
        hold(handles.axEnergy, 'on');
        stem(handles.axEnergy, n_vec, E_eV, 'filled', ...
            'Color', [0.2 0.45 0.7], 'LineWidth', 1.4, 'MarkerSize', 6);
        % Highlight current n
        stem(handles.axEnergy, n, energy_eV(n, L, m_e), 'filled', ...
            'Color', [0.85 0.25 0.15], 'LineWidth', 2.0, 'MarkerSize', 9);
        xlim(handles.axEnergy, [0.5 15.5]);
        title(handles.axEnergy, sprintf( ...
            'Energy levels  (current n = %d highlighted)', n), ...
            'Color', [0.1 0.1 0.1], 'FontSize', 12, 'FontWeight', 'bold');

        % ----- Probability density -----
        x_nm = linspace(0, L_nm, 600);
        x    = x_nm * 1e-9;

        cla(handles.axProb);
        hold(handles.axProb, 'on');

        if handles.chkOverlay.Value
            colors = lines(5);
            for k = 1:5
                psi2 = prob_density(k, x, L);
                plot(handles.axProb, x_nm, psi2*1e-9, ...
                    'Color', colors(k,:), 'LineWidth', 1.6, ...
                    'DisplayName', sprintf('n = %d', k));
            end
            legend(handles.axProb, 'Location', 'northeast', 'FontSize', 9);
        else
            psi2 = prob_density(n, x, L);
            area(handles.axProb, x_nm, psi2*1e-9, ...
                'FaceColor', [0.35 0.65 0.95], 'FaceAlpha', 0.45, ...
                'EdgeColor', [0.15 0.35 0.65], 'LineWidth', 1.8);
            % Classical turning walls
            xline(handles.axProb, 0, '--', 'Color', [0.5 0.5 0.5], 'LineWidth', 1.2);
            xline(handles.axProb, L_nm, '--', 'Color', [0.5 0.5 0.5], 'LineWidth', 1.2);
        end
        xlim(handles.axProb, [0 L_nm]);
        title(handles.axProb, sprintf( ...
            'Probability density |\\psi_n(x)|^{2}   (n = %d,  L = %.2f nm)', n, L_nm), ...
            'Color', [0.1 0.1 0.1], 'FontSize', 12, 'FontWeight', 'bold');

        % ----- Uncertainty plot for n = 1…15 -----
        product_over_hbar = compute_uncertainty_product(n_vec, L);

        cla(handles.axUnc);
        hold(handles.axUnc, 'on');
        plot(handles.axUnc, n_vec, product_over_hbar, 'o-', ...
            'Color', [0.2 0.5 0.3], 'LineWidth', 1.6, ...
            'MarkerFaceColor', [0.3 0.7 0.4]);
        yline(handles.axUnc, 0.5, '--r', 'LineWidth', 1.8, ...
            'Label', 'ħ/2', 'LabelHorizontalAlignment', 'left', ...
            'FontSize', 10, 'Color', [0.7 0.1 0.1]);
        % Current n
        plot(handles.axUnc, n, product_over_hbar(n), 's', ...
            'MarkerSize', 11, 'MarkerFaceColor', [0.85 0.25 0.15], ...
            'MarkerEdgeColor', [0.5 0.1 0.05], 'LineWidth', 1.5);
        xlim(handles.axUnc, [0.5 15.5]);
        ylim(handles.axUnc, [0 max(product_over_hbar)*1.15]);
        title(handles.axUnc, 'Uncertainty product  \Delta x·\Delta p / ħ   (always ≥ ½)', ...
            'Color', [0.1 0.1 0.1], 'FontSize', 12, 'FontWeight', 'bold');

        % ----- Live numerical panel -----
        [dx, dp, product] = single_uncertainty(n, L);
        E = energy_eV(n, L, m_e);
        lines = {
            sprintf('Quantum number n = %d', n)
            sprintf('Box width L = %.3f nm', L_nm)
            sprintf('Energy E_n = %.4f eV', E)
            ''
            sprintf('Δx = %.4e m', dx)
            sprintf('Δp = %.4e kg·m/s', dp)
            sprintf('Δx·Δp = %.4e J·s', product)
            sprintf('ħ/2   = %.4e J·s', hbar/2)
            ''
            sprintf('Δx·Δp / (ħ/2) = %.3f   (> 1)', product/(hbar/2))
            };
        handles.txtValues.Value = lines;

        handles.lblStatus.Text = sprintf( ...
            'n = %d,  L = %.2f nm  |  E = %.3f eV  |  ΔxΔp = %.2f × (ħ/2)', ...
            n, L_nm, E, product/(hbar/2));
    end

    function E = energy_eV(n, L, m)
        % Energy in electron-volts
        E_J = (n.^2 * pi^2 * hbar^2) / (2 * m * L^2);
        E   = E_J / eV;
    end

    function P = prob_density(n, x, L)
        % |ψ_n(x)|²
        P = (2/L) * sin(n * pi * x / L).^2;
    end

    function [dx, dp, product] = single_uncertainty(n, L)
        % Analytic results for the infinite square well
        % <x>  = L/2
        % <x²> = L² (1/3 − 1/(2 π² n²))
        % <p>  = 0
        % <p²> = (n π ħ / L)²
        dx2 = L^2 * (1/3 - 1/(2*pi^2*n^2));
        dx  = sqrt(dx2);
        dp  = n * pi * hbar / L;          % since <p²> = (n π ħ / L)²
        product = dx * dp;
    end

    function product_over_hbar = compute_uncertainty_product(n_vec, L)
        % Returns Δx·Δp / ħ for each quantum number in n_vec
        product_over_hbar = zeros(size(n_vec));
        for k = 1:numel(n_vec)
            [~, ~, prod] = single_uncertainty(n_vec(k), L);
            product_over_hbar(k) = prod / hbar;
        end
    end

    function highlightUncertainty()
        % Update status message with the uncertainty check
        n = round(handles.sldN.Value);
        L = handles.sldL.Value * 1e-9;
        [~, ~, product] = single_uncertainty(n, L);
        ratio = product / (hbar/2);
        handles.lblStatus.Text = sprintf( ...
            'Uncertainty Principle satisfied:  Δx·Δp = %.3f × (ħ/2)  ≥  ħ/2', ratio);
    end

    function exportResults()
        n = round(handles.sldN.Value);
        L_nm = handles.sldL.Value;
        L = L_nm * 1e-9;

        n_vec = 1:10;
        E_list = energy_eV(n_vec, L, m_e);
        prod_list = zeros(size(n_vec));
        for k = 1:numel(n_vec)
            [~, ~, prod_list(k)] = single_uncertainty(n_vec(k), L);
        end

        report = sprintf([ ...
            'PARTICLE-IN-A-BOX SIMULATION – TASK #7\n' ...
            '======================================\n' ...
            'Box width L = %.4f nm\n' ...
            'Particle mass = electron mass\n\n' ...
            'Current state n = %d\n' ...
            'Energy E_n = %.6f eV\n\n'], L_nm, n, energy_eV(n, L, m_e));

        report = [report, sprintf('n    E (eV)        Δx·Δp / (ħ/2)\n')];
        report = [report, sprintf('--------------------------------\n')];
        for k = 1:numel(n_vec)
            report = [report, sprintf('%2d   %10.5f     %8.4f\n', ...
                n_vec(k), E_list(k), prod_list(k)/(hbar/2))];
        end
        report = [report, sprintf('\nAll states satisfy Δx·Δp ≥ ħ/2.\n')];

        [file, path] = uiputfile('ParticleInABox_Results.txt', 'Save numerical results');
        if isequal(file, 0)
            handles.lblStatus.Text = 'Export cancelled.';
            return;
        end
        fid = fopen(fullfile(path, file), 'w');
        fprintf(fid, '%s', report);
        fclose(fid);
        handles.lblStatus.Text = sprintf('Exported → %s', file);
    end

end